### PR TITLE
always use random TCP ISNs for v4 and v6

### PR DESCRIPTION
**Pull request by x86pup**
referenced original in-tree patch from 0xsirus at https://github.com/anthraxx/linux-hardened/pull/26 just removed adding a sysctl to avoid needing to mess with sepolicy, and doing it for IPv6 too

had to remove the seq_scale function to resolve build error. this is fine because we're not using [unprivate timer/clock-based sequences ](https://bitguard.wordpress.com/2019/09/03/an-analysis-of-tcp-secure-sn-generation-in-linux-and-its-privacy-issues/)so this isn't relevant to us, and nothing else uses this function.

```
/opt/june/android/kernel/raviole/aosp/net/core/secure_seq.c:40:12: error: unused function 'seq_scale' [-Werror,-Wunused-function]
static u32 seq_scale(u32 seq)
           ^
1 error generated.
```

I don't have IPv6 so I can't test if the v6 part works (unless testing LAN IPv6 counts) but I tested IPv4 and basic internet activity still works.

### CODE REVIEW

**Comment by thestinger** [comment]
I don't understand what this is meant to be doing.

**Comment by x86pup** [comment]
See https://bitguard.wordpress.com/2019/09/03/an-analysis-of-tcp-secure-sn-generation-in-linux-and-its-privacy-issues/, https://forums.whonix.org/t/tcp-isn-cpu-information-leak-protection-tirdad/8552, and the original Tirdad module https://github.com/0xsirus/tirdad

**Comment by x86pup** [comment]
This always uses a random ISN sequence instead of putting it behind a sysctl, or using the tirdad kernel module (which is GPLv3 anyways) by replacing the current logic of generating an ISN.

**Comment by thestinger** [comment]
This seems to break TCP timestamps instead of fixing an issue with them.

**Pull request closed without merging**
